# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('ts', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование бренда')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('ts', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=64, verbose_name='Группа товара')),
                ('hidden', models.BooleanField(default=True, verbose_name='Уровень каталога')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('ts', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('object_id', models.PositiveIntegerField()),
                ('ts_start', models.DateField(blank=True, null=True, verbose_name='Начало действия скидки')),
                ('ts_end', models.DateField(blank=True, null=True, verbose_name='Начало действия скидки')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Скидка в рублях')),
                ('discount_percent', models.PositiveSmallIntegerField(verbose_name='Скидка в %')),
                ('email', models.EmailField(max_length=254, verbose_name='Скидка для пользователя')),
                ('short_desc', models.CharField(max_length=500, verbose_name='Название/описание')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Скидочный код')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('ts', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=128, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость, руб.')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость со скидкой, руб.')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='Группа')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
