# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, null=True, verbose_name='Slug'),
        ),
    ]
