# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170816_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Скидка в %'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Скидка в рублях'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Скидка для пользователя'),
        ),
    ]
